"""Add FlowIQ tables for interactive flows

Revision ID: 494eb415fa85
Revises: 32ef35f61b07
Create Date: 2025-07-06 19:41:19.957583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '494eb415fa85'
down_revision: Union[str, None] = '32ef35f61b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=True),
    sa.Column('trigger_delay', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flows_id'), 'flows', ['id'], unique=False)
    op.create_index(op.f('ix_flows_tenant_id'), 'flows', ['tenant_id'], unique=False)
    op.create_table('flow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=False),
    sa.Column('content_ar', sa.Text(), nullable=False),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('animation_type', sa.String(length=50), nullable=True),
    sa.Column('animation_duration', sa.Integer(), nullable=True),
    sa.Column('delay_before', sa.Integer(), nullable=True),
    sa.Column('option1_text_ar', sa.String(length=255), nullable=True),
    sa.Column('option1_text_en', sa.String(length=255), nullable=True),
    sa.Column('option1_next_step_id', sa.Integer(), nullable=True),
    sa.Column('option1_action', sa.String(length=100), nullable=True),
    sa.Column('option2_text_ar', sa.String(length=255), nullable=True),
    sa.Column('option2_text_en', sa.String(length=255), nullable=True),
    sa.Column('option2_next_step_id', sa.Integer(), nullable=True),
    sa.Column('option2_action', sa.String(length=100), nullable=True),
    sa.Column('option3_text_ar', sa.String(length=255), nullable=True),
    sa.Column('option3_text_en', sa.String(length=255), nullable=True),
    sa.Column('option3_next_step_id', sa.Integer(), nullable=True),
    sa.Column('option3_action', sa.String(length=100), nullable=True),
    sa.Column('option4_text_ar', sa.String(length=255), nullable=True),
    sa.Column('option4_text_en', sa.String(length=255), nullable=True),
    sa.Column('option4_next_step_id', sa.Integer(), nullable=True),
    sa.Column('option4_action', sa.String(length=100), nullable=True),
    sa.Column('default_next_step_id', sa.Integer(), nullable=True),
    sa.Column('auto_advance', sa.Boolean(), nullable=True),
    sa.Column('auto_advance_delay', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_next_step_id'], ['flow_steps.id'], ),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.ForeignKeyConstraint(['option1_next_step_id'], ['flow_steps.id'], ),
    sa.ForeignKeyConstraint(['option2_next_step_id'], ['flow_steps.id'], ),
    sa.ForeignKeyConstraint(['option3_next_step_id'], ['flow_steps.id'], ),
    sa.ForeignKeyConstraint(['option4_next_step_id'], ['flow_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_steps_flow_id'), 'flow_steps', ['flow_id'], unique=False)
    op.create_index(op.f('ix_flow_steps_id'), 'flow_steps', ['id'], unique=False)
    op.create_table('flow_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('last_step_id', sa.Integer(), nullable=True),
    sa.Column('steps_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.ForeignKeyConstraint(['last_step_id'], ['flow_steps.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_interactions_flow_id'), 'flow_interactions', ['flow_id'], unique=False)
    op.create_index(op.f('ix_flow_interactions_id'), 'flow_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_flow_interactions_session_id'), 'flow_interactions', ['session_id'], unique=False)
    op.create_index(op.f('ix_flow_interactions_tenant_id'), 'flow_interactions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flow_interactions_tenant_id'), table_name='flow_interactions')
    op.drop_index(op.f('ix_flow_interactions_session_id'), table_name='flow_interactions')
    op.drop_index(op.f('ix_flow_interactions_id'), table_name='flow_interactions')
    op.drop_index(op.f('ix_flow_interactions_flow_id'), table_name='flow_interactions')
    op.drop_table('flow_interactions')
    op.drop_index(op.f('ix_flow_steps_id'), table_name='flow_steps')
    op.drop_index(op.f('ix_flow_steps_flow_id'), table_name='flow_steps')
    op.drop_table('flow_steps')
    op.drop_index(op.f('ix_flows_tenant_id'), table_name='flows')
    op.drop_index(op.f('ix_flows_id'), table_name='flows')
    op.drop_table('flows')
    # ### end Alembic commands ###
