"""Add multi-item badge text customization fields

Revision ID: d16207eed0c2
Revises: 84d57b7c8655
Create Date: 2025-07-10 01:04:28.048887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16207eed0c2'
down_revision: Union[str, None] = '84d57b7c8655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_items_parent_item_id'), table_name='menu_items')
    op.add_column('settings', sa.Column('multi_item_badge_text_en', sa.String(length=50), nullable=True))
    op.add_column('settings', sa.Column('multi_item_badge_text_ar', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'multi_item_badge_text_ar')
    op.drop_column('settings', 'multi_item_badge_text_en')
    op.create_index(op.f('ix_menu_items_parent_item_id'), 'menu_items', ['parent_item_id'], unique=False)
    # ### end Alembic commands ###
