"""Add multi-item badge color field

Revision ID: d2423f523452
Revises: d16207eed0c2
Create Date: 2025-07-10 01:16:35.622604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2423f523452'
down_revision: Union[str, None] = 'd16207eed0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('multi_item_badge_color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'multi_item_badge_color')
    # ### end Alembic commands ###
